name: 'Initialize'
description: 'Initialize the workspace (checkout, auth, setup node)'
inputs:
  node-version:
    description: 'The version of node to use (default: 20)'
    required: false
    default: 20
  username:
    description: 'The username for authentication'
    required: true
  password:
    description: 'The password/token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    # Checkout/get the latest code
    - uses: actions/checkout@v3

    # Authenticate
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    # Set up node with the specified version
    - uses: actions/setup-node@v3 v${{ inputs.node-version }}
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://npm.pkg.github.com
        scope: "@neverendingsupport"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.password }}