
name: Run Snyk Scan
description: Runs Snyk Scan

inputs:
  snykToken:
    description: The snyk token used to access snyk cloud and/or run scan
    required: true
  snykThreshold:
    description: The snyk threshold to fail on
    default: medium
    required: false
  policyPath:
    description: The path to the .snyk file that establishes policy exceptions for a given repo
    required: false

runs:
  using: composite
  steps:

    - name: Run Snyk to check for vulnerabilities
      if: ${{ inputs.policyPath == '' }}
      uses: snyk/actions/node@master
      with:
        args: --severity-threshold=${{ inputs.snykThreshold }} --all-projects --org=${{ secrets.SNYK_ORG_ID }}
      env:
        SNYK_TOKEN: ${{ inputs.snykToken }}

    - name: Run Snyk to check for vulnerabilities
      if: ${{ inputs.policyPath != '' }}
      uses: snyk/actions/node@master
      with:
        args: --severity-threshold=${{ inputs.snykThreshold }} --all-projects --policy-path=${{ inputs.policyPath }} --org=${{ secrets.SNYK_ORG_ID }}
      env:
        SNYK_TOKEN: ${{ inputs.snykToken }}
